// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwzCvtQhNiOIQstN_2j-YSI5ZlBJ4TrEA',
    appId: '1:83171344204:web:2411308f89e3d82e3fd9e9',
    messagingSenderId: '83171344204',
    projectId: 'project-f2b339b0-5b01-4c3c-b5e',
    authDomain: 'project-f2b339b0-5b01-4c3c-b5e.firebaseapp.com',
    storageBucket: 'project-f2b339b0-5b01-4c3c-b5e.firebasestorage.app',
    measurementId: 'G-5CKG9QC861',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeStw8HiKv_0IUTGbHgGjD1_TpMtpc9RU',
    appId: '1:83171344204:android:d0f5b99aae8c58463fd9e9',
    messagingSenderId: '83171344204',
    projectId: 'project-f2b339b0-5b01-4c3c-b5e',
    storageBucket: 'project-f2b339b0-5b01-4c3c-b5e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiziKsOrOWkxNG_XksgGPDBl0Wrakisic',
    appId: '1:83171344204:ios:b2fa711d9d92a2e93fd9e9',
    messagingSenderId: '83171344204',
    projectId: 'project-f2b339b0-5b01-4c3c-b5e',
    storageBucket: 'project-f2b339b0-5b01-4c3c-b5e.firebasestorage.app',
    iosBundleId: 'com.example.crudGetxFirebase',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiziKsOrOWkxNG_XksgGPDBl0Wrakisic',
    appId: '1:83171344204:ios:b2fa711d9d92a2e93fd9e9',
    messagingSenderId: '83171344204',
    projectId: 'project-f2b339b0-5b01-4c3c-b5e',
    storageBucket: 'project-f2b339b0-5b01-4c3c-b5e.firebasestorage.app',
    iosBundleId: 'com.example.crudGetxFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwzCvtQhNiOIQstN_2j-YSI5ZlBJ4TrEA',
    appId: '1:83171344204:web:2aa8951bd3f4bd8f3fd9e9',
    messagingSenderId: '83171344204',
    projectId: 'project-f2b339b0-5b01-4c3c-b5e',
    authDomain: 'project-f2b339b0-5b01-4c3c-b5e.firebaseapp.com',
    storageBucket: 'project-f2b339b0-5b01-4c3c-b5e.firebasestorage.app',
    measurementId: 'G-BQQ49MW30C',
  );
}
